/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.test.junit4.test;

import gradle.test.junit4.domain.User;
import org.apache.http.HttpStatus;
import org.junit.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

public class AppTest extends BaseTest{

    private static final String LIST_USERS_ENDPOINT = "/users";
    private static final String CREATE_USER_ENDPOINT = "/user";
    private static final String SHOW_USER_ENDPOINT = "/users/{userId}";

    @Test
    public void testShowSpecificUser() {
        User user = given().log().all().
                pathParam("userId", 2).
                when().
                get(SHOW_USER_ENDPOINT).
                then().log().all().
                statusCode(HttpStatus.SC_OK).
                extract().
                body().jsonPath().getObject("data", User.class);


        assertThat(user.getEmail(), containsString("@reqres.in"));
        assertThat(user.getName(), containsString("Janet"));
        assertThat(user.getLastName(), containsString("Weaver"));
    }

}
